@Api_HostAddress = http://localhost:5116

POST {{Api_HostAddress}}/api/customers
Content-Type: application/json

{
    "name": "John Doe",
    "cpf": "249.715.637-92",
    "email": "john@email.com",
    "address": {
        "street": "Wonderful Street",
        "neighborhood": "Wonderful Neighborhood",
        "city": "Wonderful City",
        "state": "Wonderful State"
    },
    "phone": "+55 (11) 91234-5678"
}

###
