@Api_HostAddress = http://localhost:5116

POST {{Api_HostAddress}}/api/customers
Content-Type: application/json

{
    "name": "John Doe",
    "cpf": "249.715.637-92",
    "email": "john@email.com",
    "address": {
        "street": "Wonderful Street",
        "neighborhood": "Wonderful Neighborhood",
        "city": "Wonderful City",
        "state": "Wonderful State"
    },
    "phone": "+55 (11) 91234-5678"
}

###

POST  {{Api_HostAddress}}/api/plans
Content-Type: application/json

{
    "name": "Premium academy",
    "description": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    "monthlyPrice": 55.99
}

###

POST  {{Api_HostAddress}}/api/subscriptions
Content-Type: application/json

{
    "StartDate": "2025-09-18",
    "EntDate": "2026-09-18",
    "IsActive": true,
    "DueDate": 20,
    "CustomerId": "b829b636-5746-4f15-8bfb-eb545ed6ff51",
    "PlanId": "a5a57fe2-33d5-4eaa-876e-f77d42cc9daa"
}